import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center w-full  bg-stone-200`}
      >
        <div className="bg-white w-full p-4 fixed flex justify-center">
          <div className="flex w-3/5">
            <h3 className="text-lg font-bold">Kerjoo Blog</h3>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
